DROP DATABASE IF EXISTS PARKING;
CREATE DATABASE PARKING;
USE PARKING;

CREATE TABLE ESTADOS (
  ESTADO_ID TINYINT(1) PRIMARY KEY,
  NombreEstado VARCHAR(10) NOT NULL
);

CREATE TABLE TIPO_VEHICULO (
  TIPOVEH_ID TINYINT(1) PRIMARY KEY,
  TipoNombre VARCHAR(10) UNIQUE NOT NULL,
  Tarifa FLOAT NOT NULL
);

CREATE TABLE PAGO (
  METODOPAGO_ID TINYINT(1) PRIMARY KEY,
  NombrePago VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE TURNO (
	TURNO_ID BIT PRIMARY KEY,
    Turno_Nombre VARCHAR(10)
);

CREATE TABLE VEHICULO (
  VEH_ID INT PRIMARY KEY AUTO_INCREMENT,
  PLACA VARCHAR(10),
  TIPOVEH_ID TINYINT(1) NOT NULL,
  Fecha_Registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Marca VARCHAR(20) NOT NULL,
  CONSTRAINT fk_vehiculoVehTipoVeh FOREIGN KEY (TIPOVEH_ID) REFERENCES TIPO_VEHICULO(TIPOVEH_ID)
);

CREATE TABLE PARQUEADERO (
  PARQ_ID TINYINT(1) PRIMARY KEY,
  CapacTotal INT NOT NULL,
  CuposOcupados INT NOT NULL DEFAULT 0,
  ESTADO_ID TINYINT(1) NOT NULL,
  CONSTRAINT chk_Cupos CHECK (CuposOcupados <= CapacTotal),
  CONSTRAINT fk_ParqEstado FOREIGN KEY (ESTADO_ID) REFERENCES ESTADOS(ESTADO_ID)
);

CREATE TABLE EMPLEADO (
  EMPLEADO_ID INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(20) NOT NULL,
  TURNO_ID BIT NOT NULL,
  Cargo VARCHAR(20) NOT NULL,
  PARQ_ID TINYINT(1) NOT NULL,
  CONSTRAINT fk_turno FOREIGN KEY (TURNO_ID) REFERENCES TURNO(TURNO_ID),
  CONSTRAINT fk_EmpleadoParq FOREIGN KEY (PARQ_ID) REFERENCES PARQUEADERO(PARQ_ID)
);

CREATE TABLE REGISTRO (
  REGISTRO_ID INT PRIMARY KEY AUTO_INCREMENT,
  VEH_ID INT NOT NULL,
  EMPLEADO_ID INT NOT NULL,
  PARQ_ID TINYINT(1) NOT NULL,
  Fecha_ingreso DATETIME NOT NULL,
  Fecha_salida DATETIME,
  CONSTRAINT fk_RegistroVeh FOREIGN KEY (VEH_ID) REFERENCES VEHICULO(VEH_ID),
  CONSTRAINT fk_RegistroEmpleado FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADO(EMPLEADO_ID),
  CONSTRAINT fk_RegistroParq FOREIGN KEY (PARQ_ID) REFERENCES PARQUEADERO(PARQ_ID)
);

CREATE TABLE FACTURA (
  FACTURA_ID INT PRIMARY KEY AUTO_INCREMENT,
  REGISTRO_ID INT NOT NULL UNIQUE,
  METODOPAGO_ID TINYINT(1) NOT NULL,
  Fecha_Factura DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Duracion INT NOT NULL,
  TotalPago FLOAT NOT NULL,
  CONSTRAINT fk_FacturaRegistro FOREIGN KEY (REGISTRO_ID) REFERENCES REGISTRO(REGISTRO_ID),
  CONSTRAINT fk_FacturaPago FOREIGN KEY (METODOPAGO_ID) REFERENCES PAGO(METODOPAGO_ID)
);
