SELECT VEHICULO.PLACA_ID, tipo_vehiculo.TipoNombre FROM VEHICULO
JOIN TIPO_VEHICULO on VEHICULO.TIPOVEH_ID = tipo_vehiculo.TIPOVEH_ID;

SELECT FACTURA.FACTURA_ID, PAGO.NOMBREPAG FROM factura
JOIN PAGO on FACTURA.METODOPAGO_ID = PAGO.METODOPAGO_ID;

SELECT f.FACTURA_ID, f.REGISTRO_ID, p.NOMBREPAG, f.FECHA_FACTURA, f.DURACION, f.TOTALPAGO FROM factura as f 
JOIN PAGO as p on f.Nombrepag = p.Metodopago_id;

