DROP DATABASE IF EXISTS Parqueadero;
CREATE DATABASE Parqueadero;
USE Parqueadero;

CREATE TABLE ESTADOS (
  Estado_ID TINYINT(1) PRIMARY KEY,
  NombreEstado VARCHAR(10) NOT NULL
);

CREATE TABLE TIPO_VEHICULO (
  TipoVeh_ID TINYINT(1) PRIMARY KEY,
  TipoNombre VARCHAR(10) UNIQUE NOT NULL,
  Tarifa FLOAT NOT NULL
);

CREATE TABLE PAGO (
  MetodoPag_ID TINYINT(1) PRIMARY KEY,
  NombrePag VARCHAR(10) UNIQUE NOT NULL
);

CREATE TABLE TURNO (
	TURNO_ID BIT PRIMARY KEY,
    Turno_Nombre VARCHAR(10)
);

CREATE TABLE VEHICULO (
  Placa_ID VARCHAR(10) PRIMARY KEY,
  TipoVeh_ID TINYINT(1) NOT NULL,
  Fecha_Registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Marca VARCHAR(20) NOT NULL,
  CONSTRAINT fk_vehiculoVehTipoVeh FOREIGN KEY (TipoVeh_ID) REFERENCES TIPO_VEHICULO(TipoVeh_ID)
);

CREATE TABLE PARQUEADERO (
  Parqueadero_ID TINYINT(1) PRIMARY KEY,
  CapacTotal INT NOT NULL,
  CuposOcupados INT NOT NULL DEFAULT 0,
  Estado_ID TINYINT(1) NOT NULL,
  CONSTRAINT chk_Cupos CHECK (CuposOcupados <= CapacTotal),
  CONSTRAINT fk_ParqEstado FOREIGN KEY (Estado_ID) REFERENCES ESTADOS(Estado_ID)
);

CREATE TABLE EMPLEADO (
  Empleado_ID INT PRIMARY KEY AUTO_INCREMENT,
  Nombre VARCHAR(20) NOT NULL,
  TURNO_ID BIT NOT NULL,
  Cargo VARCHAR(20) NOT NULL,
  Parqueadero_ID TINYINT(1) NOT NULL,
  CONSTRAINT fk_turno FOREIGN KEY (TURNO_ID) REFERENCES TURNO(TURNO_ID),
  CONSTRAINT fk_EmpleadoParq FOREIGN KEY (Parqueadero_ID) REFERENCES PARQUEADERO(Parqueadero_ID)
);

CREATE TABLE REGISTRO (
  Registro_ID INT PRIMARY KEY AUTO_INCREMENT,
  Placa_ID VARCHAR(10) NOT NULL,
  Empleado_ID INT NOT NULL,
  Parqueadero_ID TINYINT(1) NOT NULL,
  Fecha_ingreso DATETIME NOT NULL,
  Fecha_salida DATETIME,
  CONSTRAINT fk_RegistroUsuario FOREIGN KEY (Placa_ID) REFERENCES VEHICULO(Placa_ID),
  CONSTRAINT fk_RegistroEmpleado FOREIGN KEY (Empleado_ID) REFERENCES EMPLEADO(Empleado_ID),
  CONSTRAINT fk_RegistroParq FOREIGN KEY (Parqueadero_ID) REFERENCES PARQUEADERO(Parqueadero_ID)
);

CREATE TABLE FACTURA (
  Factura_ID INT PRIMARY KEY AUTO_INCREMENT,
  Registro_ID INT NOT NULL UNIQUE,
  MetodoPag_ID TINYINT(1) NOT NULL,
  Fecha_Factura DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Duracion INT NOT NULL,
  TotalPago FLOAT NOT NULL,
  CONSTRAINT fk_FacturaRegistro FOREIGN KEY (Registro_ID) REFERENCES REGISTRO(Registro_ID),
  CONSTRAINT fk_FacturaPago FOREIGN KEY (MetodoPag_ID) REFERENCES PAGO(MetodoPag_ID)
);

